CREATE TABLE users (
	idUSERS BIGINT UNSIGNED AUTO_INCREMENT,
	user_code BIGINT UNSIGNED NOT NULL,
	fname VARCHAR(20) NOT NULL,
	lname VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	email2 VARCHAR(50),
	password VARCHAR(50) NOT NULL,
	user VARCHAR(50), 
	user_type VARCHAR(10) NOT NULL,
	gender VARCHAR(10) NOT NULL,
	address1 VARCHAR(50) NOT NULL,
	city VARCHAR(25),
	state VARCHAR(25),
	zip VARCHAR(10),
	avatar VARCHAR(255),
	created_at TIMESTAMP,
    PRIMARY KEY (idUSERS)
);